name: "static analysis"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  validate:
    name: validate
    runs-on: ubuntu-latest
    strategy:
      matrix:
        terraform: [ ~1.5, latest ]
    steps:
      - uses: actions/checkout@v5

      - uses: actions/cache@v4
        with:
          path: ~/.tflint.d/plugins
          key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ matrix.terraform }}

      - uses: terraform-linters/setup-tflint@ae78205cfffec9e8d93fd2b3115c7e9d3166d4b6 # v5.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - uses: aquasecurity/setup-trivy@v0.2.4

      - run: make